ime_studenta = input('Ime : ')
prezime_studenta = input ('Prezime : ')
student_oib = int(input('Oib : '))
student_email = input('Email adresa : ')
student_broj_telefona = input('Broj telefona : ')
godina_upisa = int(input('Godina upisa : '))
naziv_studija = input('Naziv studija : ')
naziv_sveucilista = input('Naziv sveučilišta : ')
ocjena_studenta = float(input('Prosječna ocjena studenta : '))
student_diplomirao = input('Da li je student uspješno diplomirao ? ')


print('Podaci o studentu:')
print('Ime:', ime_studenta)
print('Prezime:', prezime_studenta)
print('OIB:', student_oib)
print('Email:', student_email)
print('Broj telefona:', student_broj_telefona)
print('Godina upisa:', godina_upisa)
print('Naziv studija:', naziv_studija)
print('Naziv sveučilišta:', naziv_sveucilista)
print('Prosječna ocjena: {:.2f}'.format(ocjena_studenta))
print('Diplomirao:', student_diplomirao)
